name: "devrelease:docker"

on:
  push:
    branches:
      - master
      - release-*
    paths:
      - .github/workflows/publish_canary_docker.yml
      - Dockerfile.*
      - scripts/CLI_VERSION
      - **/pom.xml
jobs:
  publish-canary-docker:
    name: "publish to DockerHub"
    # We use `docker push --all-tags` to push all tags which is a newly addition to docker
    runs-on: ubuntu-20.04
    if: github.repository == 'microsoft/playwright-java'
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: playwright.azurecr.io
        username: playwright
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t playwright-java:localbuild-focal -f Dockerfile.focal .
    - name: tag & publish
      run: |
        ./utils/docker/tag_image_and_push.sh playwright-java:localbuild-focal playwright.azurecr.io/public/playwright/java:next
        ./utils/docker/tag_image_and_push.sh playwright-java:localbuild-focal playwright.azurecr.io/public/playwright/java:next-focal
        ./utils/docker/tag_image_and_push.sh playwright-java:localbuild-focal playwright.azurecr.io/public/playwright/java:sha-${{ github.sha }}
